//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_Bonos
    {
        public int idBono { get; set; }
        public Nullable<int> idResponsableAlmacen { get; set; }
        public string nombreResponsableAlmacen { get; set; }
        public Nullable<int> idAlmacen { get; set; }
        public string nombreAlmacen { get; set; }
        public Nullable<decimal> montoVenta { get; set; }
        public Nullable<decimal> manejoCDA { get; set; }
        public Nullable<decimal> montoPolitica { get; set; }
        public Nullable<decimal> cantidadInicial { get; set; }
        public Nullable<decimal> cantidadTopada { get; set; }
        public Nullable<int> numVecesPremio { get; set; }
        public Nullable<decimal> montoBonoManejoCDA { get; set; }
        public Nullable<decimal> MontoBonoPolitica { get; set; }
        public Nullable<int> idPolitica { get; set; }
        public Nullable<decimal> TotalBono { get; set; }
        public Nullable<int> idConcepto { get; set; }
        public string descripcionConcepto { get; set; }
        public Nullable<int> idPeriodo { get; set; }
    }
}
