//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models.ModelsEvolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_tb_Customer
    {
        public string partner_id { get; set; }
        public string last_name { get; set; }
        public string second_last_name { get; set; }
        public string midle_name { get; set; }
        public string first_name { get; set; }
        public string sponsor_id { get; set; }
        public string upline_id { get; set; }
        public string PostalCode { get; set; }
        public string country_id { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Address_3 { get; set; }
        public string Postal_Community_id { get; set; }
        public string city_id { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<long> Mapanet_id { get; set; }
        public string language_id { get; set; }
        public string Phone_number { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<int> tax_id_type { get; set; }
        public string tax_id { get; set; }
        public string social_security { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string brith_city { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string co_owner { get; set; }
        public Nullable<System.DateTime> co_owner_brithdate { get; set; }
        public string co_owner_email { get; set; }
        public string co_owner_telefhono { get; set; }
        public string co_owner_mobile { get; set; }
        public Nullable<int> pickupcenter_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string account { get; set; }
        public Nullable<int> account_type { get; set; }
        public string account_Principal { get; set; }
        public Nullable<int> active_account { get; set; }
        public Nullable<int> tax_type { get; set; }
        public Nullable<decimal> tax_percent { get; set; }
        public Nullable<decimal> sales_tax_withold { get; set; }
        public string comments { get; set; }
        public Nullable<int> partner_status_id { get; set; }
        public Nullable<System.DateTime> first_purchase_date { get; set; }
        public Nullable<System.DateTime> last_purchase_date { get; set; }
        public string customer_type { get; set; }
        public Nullable<int> id_type { get; set; }
        public string id_number { get; set; }
        public Nullable<int> current_grade_level { get; set; }
        public Nullable<System.DateTime> maximum_grade_level_date { get; set; }
        public Nullable<int> maximum_grade_level { get; set; }
        public Nullable<int> last_grade_level { get; set; }
        public string marketing_plan { get; set; }
        public string registration_method { get; set; }
        public Nullable<int> personal_type { get; set; }
        public Nullable<int> profession_id { get; set; }
        public Nullable<int> Marital_status { get; set; }
        public Nullable<int> hold_payment { get; set; }
        public Nullable<int> contact_us { get; set; }
        public string web_user_name { get; set; }
        public string Web_password { get; set; }
        public Nullable<bool> old_id_number { get; set; }
        public Nullable<int> promotion_code { get; set; }
        public string price_type { get; set; }
        public Nullable<int> personal_business { get; set; }
        public string offical_image_id_one { get; set; }
        public string offical_image_id_two { get; set; }
        public string creator_user { get; set; }
        public Nullable<System.DateTime> creator_date { get; set; }
        public string creator_machine { get; set; }
        public string changing_user { get; set; }
        public Nullable<System.DateTime> changing_date { get; set; }
        public string changing_machine { get; set; }
        public Nullable<int> RankLastPeriod_ID { get; set; }
        public Nullable<int> RankCurrent_ID { get; set; }
        public Nullable<int> RankMaximum_ID { get; set; }
        public Nullable<int> RankMaximumDate { get; set; }
        public Nullable<int> Paymethod_com { get; set; }
        public string Xen_Email { get; set; }
        public string Xen_WorkNo { get; set; }
        public string Xen_HomeNo { get; set; }
        public string Xen_CellNo { get; set; }
        public string Xen_ShippingAddress1 { get; set; }
        public string Xen_ShippingAddress2 { get; set; }
        public string Xen_ShippingAddress3 { get; set; }
        public string Xen_ShippingCity { get; set; }
        public string Xen_ShippingState { get; set; }
        public string Xen_ShippingCountry { get; set; }
        public string Xen_ShippingZip { get; set; }
        public string Xen_BillingCity { get; set; }
        public string Xen_BillingState { get; set; }
        public Nullable<short> Xen_DistBusinessCenter { get; set; }
        public string Xen_EnteredBy { get; set; }
        public string Xen_DefaultWarehouse { get; set; }
        public Nullable<int> Xen_Active { get; set; }
    }
}
