//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models.ModelsEvolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_tb_Pais
    {
        public int Id_Pais { get; set; }
        public byte Id_Estatus { get; set; }
        public string Pais { get; set; }
        public string Folio { get; set; }
        public string NombreCorto { get; set; }
        public Nullable<int> DistBusinessCenter { get; set; }
        public string Warehouse { get; set; }
        public int Id_PaisXe { get; set; }
    }
}
