//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models.ModelsEvolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_Rank
    {
        public int Rank_ID { get; set; }
        public int Rank_XEID { get; set; }
        public string Rank { get; set; }
        public string Rank_XE { get; set; }
        public int type_Id { get; set; }
        public Nullable<decimal> PV { get; set; }
        public int DirectQualified { get; set; }
        public System.DateTime F_Creation { get; set; }
        public string U_Creation { get; set; }
        public string H_Creation { get; set; }
        public Nullable<System.DateTime> F_Modified { get; set; }
        public string U_Modified { get; set; }
        public string H_Modified { get; set; }
    }
}
