//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models.ModelsEvolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_tb_TipoCambio
    {
        public int Id_Reg { get; set; }
        public int DistBusinessCenter { get; set; }
        public string Moneda { get; set; }
        public string Abreviatura { get; set; }
        public int id_moneda { get; set; }
        public string Currency { get; set; }
        public string LCurrency { get; set; }
        public string Order_Currency_Code { get; set; }
        public int id_vigente { get; set; }
        public decimal valor { get; set; }
        public Nullable<System.DateTime> f_VigenciaInicio { get; set; }
        public Nullable<System.DateTime> f_VigenciaFin { get; set; }
    }
}
