//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models.ModelsEvolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_tb_Products
    {
        public string sku { get; set; }
        public string warehouse { get; set; }
        public string Id_Empresa { get; set; }
        public int Warehouse_ID { get; set; }
        public string cve_art { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public Nullable<double> PrecioPublico { get; set; }
        public Nullable<double> PrecioMinimo { get; set; }
        public Nullable<double> PrecioCosto { get; set; }
        public Nullable<double> PrecioSocio { get; set; }
        public Nullable<double> XPrecioPublicoL { get; set; }
        public decimal XPrecioPublicoDescL { get; set; }
        public Nullable<double> XPrecioSocioL { get; set; }
        public decimal XPrecioSocioDescL { get; set; }
        public Nullable<double> XPrecioPrefL { get; set; }
        public decimal XPrecioPrefDescL { get; set; }
        public Nullable<double> XPrecioPublico { get; set; }
        public decimal XPrecioPublicoDesc { get; set; }
        public Nullable<double> XPrecioSocio { get; set; }
        public decimal XPrecioSocioDesc { get; set; }
        public Nullable<double> XPrecioPref { get; set; }
        public decimal XPrecioPrefDesc { get; set; }
        public Nullable<double> PuntosPersonal { get; set; }
        public Nullable<double> PuntosPersonalDesc { get; set; }
        public Nullable<double> PuntosComision { get; set; }
        public Nullable<double> PuntosComisionDesc { get; set; }
        public string ActivoSAE { get; set; }
    }
}
