//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models.ModelsEvolution
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EvolutionEntities : DbContext
    {
        public EvolutionEntities()
            : base("name=EvolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CU_tb_Mes> CU_tb_Mes { get; set; }
        public virtual DbSet<CL_tb_Pais> CL_tb_Pais { get; set; }
        public virtual DbSet<CO_tb_Periodo> CO_tb_Periodo { get; set; }
        public virtual DbSet<CO_tb_Rank> CO_tb_Rank { get; set; }
        public virtual DbSet<CU_tb_Periodo> CU_tb_Periodo { get; set; }
        public virtual DbSet<CU_tb_TipoCambio> CU_tb_TipoCambio { get; set; }
        public virtual DbSet<IN_tb_Products> IN_tb_Products { get; set; }
        public virtual DbSet<CL_tb_Customer> CL_tb_Customer { get; set; }
        public virtual DbSet<CL_tb_CustomerRank> CL_tb_CustomerRank { get; set; }
        public virtual DbSet<CO_tb_cdaPolitica> CO_tb_cdaPolitica { get; set; }
        public virtual DbSet<CO_tb_TypeDist> CO_tb_TypeDist { get; set; }
    
        public virtual int CL_sp_pr_CrearRed(string pnId_Cliente)
        {
            var pnId_ClienteParameter = pnId_Cliente != null ?
                new ObjectParameter("pnId_Cliente", pnId_Cliente) :
                new ObjectParameter("pnId_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CL_sp_pr_CrearRed", pnId_ClienteParameter);
        }
    
        public virtual int CL_stp_in_order()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CL_stp_in_order");
        }
    
        public virtual int CU_sp_se_Folio(string id_Empresa, Nullable<int> pnId_Foliador, ObjectParameter pnFolio)
        {
            var id_EmpresaParameter = id_Empresa != null ?
                new ObjectParameter("Id_Empresa", id_Empresa) :
                new ObjectParameter("Id_Empresa", typeof(string));
    
            var pnId_FoliadorParameter = pnId_Foliador.HasValue ?
                new ObjectParameter("pnId_Foliador", pnId_Foliador) :
                new ObjectParameter("pnId_Foliador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CU_sp_se_Folio", id_EmpresaParameter, pnId_FoliadorParameter, pnFolio);
        }
    
        public virtual int PR_sp_MailPt(string body)
        {
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_sp_MailPt", bodyParameter);
        }
    
        public virtual int SAE_stp_in_Pedidos_06(string nId_Empresa)
        {
            var nId_EmpresaParameter = nId_Empresa != null ?
                new ObjectParameter("nId_Empresa", nId_Empresa) :
                new ObjectParameter("nId_Empresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SAE_stp_in_Pedidos_06", nId_EmpresaParameter);
        }
    
        public virtual int SAE_stp_in_Pedidos_08(string nId_Empresa)
        {
            var nId_EmpresaParameter = nId_Empresa != null ?
                new ObjectParameter("nId_Empresa", nId_Empresa) :
                new ObjectParameter("nId_Empresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SAE_stp_in_Pedidos_08", nId_EmpresaParameter);
        }
    
        public virtual int SAE_stp_in_Pedidos_13(string nId_Empresa)
        {
            var nId_EmpresaParameter = nId_Empresa != null ?
                new ObjectParameter("nId_Empresa", nId_Empresa) :
                new ObjectParameter("nId_Empresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SAE_stp_in_Pedidos_13", nId_EmpresaParameter);
        }
    
        public virtual int SAE_stp_in_Pedidos03(string nId_Empresa)
        {
            var nId_EmpresaParameter = nId_Empresa != null ?
                new ObjectParameter("nId_Empresa", nId_Empresa) :
                new ObjectParameter("nId_Empresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SAE_stp_in_Pedidos03", nId_EmpresaParameter);
        }
    
        public virtual ObjectResult<stp_carga_archivo_Result> stp_carga_archivo(string fileproc)
        {
            var fileprocParameter = fileproc != null ?
                new ObjectParameter("fileproc", fileproc) :
                new ObjectParameter("fileproc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_carga_archivo_Result>("stp_carga_archivo", fileprocParameter);
        }
    
        public virtual ObjectResult<stp_carga_cliente_Result> stp_carga_cliente(string fileproc)
        {
            var fileprocParameter = fileproc != null ?
                new ObjectParameter("fileproc", fileproc) :
                new ObjectParameter("fileproc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_carga_cliente_Result>("stp_carga_cliente", fileprocParameter);
        }
    
        public virtual ObjectResult<stp_distribuye_archivo_Result> stp_distribuye_archivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_distribuye_archivo_Result>("stp_distribuye_archivo");
        }
    
        public virtual int XE_PrecioGeneracion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XE_PrecioGeneracion");
        }
    
        public virtual ObjectResult<XE_PrecioGeneracion2_Result> XE_PrecioGeneracion2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<XE_PrecioGeneracion2_Result>("XE_PrecioGeneracion2");
        }
    
        public virtual int XE_Socio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XE_Socio");
        }
    }
}
