//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_Comisiones
    {
        public int id_Comisiones { get; set; }
        public Nullable<int> id_Periodo { get; set; }
        public string partner_id { get; set; }
        public Nullable<int> id_Concepto { get; set; }
        public Nullable<System.DateTime> fechaAplicacion { get; set; }
        public decimal monto { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> folioCalculo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
        public string Clabe { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<int> idMonedaLocal { get; set; }
        public Nullable<decimal> MontoUSD { get; set; }
        public Nullable<decimal> MontoMonedaLocal { get; set; }
    }
}
