//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_PrestamoDetalle
    {
        public int id_PrestamoDetalle { get; set; }
        public Nullable<int> id_Prestamo { get; set; }
        public decimal importe { get; set; }
        public int pagonumero { get; set; }
        public System.DateTime fechaPago { get; set; }
        public System.DateTime fechaAplicacion { get; set; }
        public Nullable<int> estatus { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
    
        public virtual CO_tb_Prestamo CO_tb_Prestamo { get; set; }
    }
}
