//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_PagosRespuesta
    {
        public int id_PagosRespuesta { get; set; }
        public Nullable<int> tiporeRegistro { get; set; }
        public string cuentaDestino { get; set; }
        public string partner_id { get; set; }
        public string beneficiario { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> numeroReferencia { get; set; }
        public Nullable<System.DateTime> fechaAplicacion { get; set; }
        public string claveRastreo { get; set; }
        public string estatus { get; set; }
        public string motivoDevolucion { get; set; }
        public Nullable<int> id_Periodo { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
    }
}
