//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_Pedidos
    {
        public int Id_Pedido { get; set; }
        public string Id_MovInv { get; set; }
        public string Id_Empresa { get; set; }
        public int Id_ConcMovInv { get; set; }
        public int Id_Almacen_Origen { get; set; }
        public int Id_Almacen_Destino { get; set; }
        public byte Id_Estatus { get; set; }
        public int Id_Periodo_PT { get; set; }
        public System.DateTime F_Traspaso { get; set; }
        public string Envio { get; set; }
        public int Id_Moneda { get; set; }
        public decimal Tipo_Cambio { get; set; }
        public string DocAnt { get; set; }
        public int Total_Partidas { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal Impuesto { get; set; }
        public decimal Total { get; set; }
        public string Observaciones { get; set; }
        public string IE_Direccion { get; set; }
        public Nullable<int> IE_CP { get; set; }
        public Nullable<int> IE_Colonia { get; set; }
        public string IE_Ciudad { get; set; }
        public string IE_Estado { get; set; }
        public string IE_NombreCol { get; set; }
        public Nullable<int> IE_Id_Almacen { get; set; }
        public string IE_Telefono { get; set; }
        public string IE_Contacto { get; set; }
        public string IE_Referencias { get; set; }
        public string partner_id { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public Nullable<int> Quincena { get; set; }
        public int Id_Condicion { get; set; }
        public Nullable<decimal> Compras { get; set; }
        public Nullable<System.DateTime> F_PrimerCompra { get; set; }
        public decimal Ventas { get; set; }
        public decimal MontoCanje { get; set; }
        public decimal DiferenciaCanje { get; set; }
        public string NoGuia { get; set; }
        public Nullable<System.DateTime> F_Envio { get; set; }
        public Nullable<int> Id_Mensajeria { get; set; }
        public Nullable<int> Generar_Traspaso { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public string Usuario_Creacion { get; set; }
        public Nullable<System.DateTime> F_UltMod { get; set; }
        public string UsuarioUltMod { get; set; }
        public Nullable<int> Id_Periodo_Evo { get; set; }
    }
}
