//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_ARBOL_HIST
    {
        public string PARTNER_ID { get; set; }
        public string SPONSOR_ID { get; set; }
        public Nullable<decimal> VENTAPERSONAL { get; set; }
        public Nullable<decimal> VENTAPERSONAL_MX { get; set; }
        public Nullable<decimal> VENTAPERSONAL_US { get; set; }
        public Nullable<decimal> VENTAPERSONAL_GT { get; set; }
        public Nullable<decimal> VENTARED { get; set; }
        public Nullable<decimal> VENTARED_MX { get; set; }
        public Nullable<decimal> VENTARED_US { get; set; }
        public Nullable<decimal> VENTARED_GT { get; set; }
        public Nullable<int> IDPERIODO { get; set; }
        public Nullable<int> NUMDIAS { get; set; }
        public Nullable<int> NUMMESES { get; set; }
        public Nullable<decimal> PUNTOSPERSONAL { get; set; }
        public Nullable<decimal> PUNTOSPERSONAL_MX { get; set; }
        public Nullable<decimal> PUNTOSPERSONAL_US { get; set; }
        public Nullable<decimal> PUNTOSPERSONAL_GT { get; set; }
        public Nullable<decimal> PUNTOSRED { get; set; }
        public Nullable<decimal> PUNTOSRED_MX { get; set; }
        public Nullable<decimal> PUNTOSRED_US { get; set; }
        public Nullable<decimal> PUNTOSRED_GT { get; set; }
        public string ALMACEN { get; set; }
        public Nullable<int> SOCIOSRED { get; set; }
        public Nullable<int> AUSPICIOSPERSONAL { get; set; }
        public Nullable<int> AUSPICIOSRED { get; set; }
        public Nullable<int> DIRECTOS { get; set; }
        public Nullable<decimal> PUNTOSAUSPICIOSPERSONAL { get; set; }
        public Nullable<int> COMPRAS_2123 { get; set; }
        public Nullable<int> COMPRAS_2124 { get; set; }
        public Nullable<int> UNIDADESPERSONAL { get; set; }
        public Nullable<int> UNIDADESRED { get; set; }
        public Nullable<decimal> DESCUENTOSPERSONAL { get; set; }
        public Nullable<decimal> DESCUENTOSPERSONAL_Mx { get; set; }
        public Nullable<decimal> DESCUENTOSPERSONAL_Us { get; set; }
        public Nullable<decimal> DESCUENTOSPERSONAL_Gt { get; set; }
        public Nullable<decimal> DESCUENTOSRED { get; set; }
        public Nullable<decimal> DESCUENTOSRED_Mx { get; set; }
        public Nullable<decimal> DESCUENTOSRED_Us { get; set; }
        public Nullable<decimal> DESCUENTOSRED_Gt { get; set; }
        public string LineaCargada { get; set; }
        public Nullable<decimal> LineaCargadaPorc { get; set; }
        public string LineaCargadaSocio { get; set; }
        public Nullable<int> LineaCargadaGrado { get; set; }
        public Nullable<decimal> Venta_4a_Generacion { get; set; }
        public Nullable<decimal> Venta_5a_Generacion { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
    }
}
