//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_PagoSocio
    {
        public int id_PagoSocio { get; set; }
        public string partner_id { get; set; }
        public decimal monto { get; set; }
        public Nullable<int> id_Periodo { get; set; }
        public Nullable<int> id_CompaniaPago { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public short estatus { get; set; }
        public Nullable<int> folioCalculo { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
        public string clabe { get; set; }
    }
}
