//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_tb_Roles()
        {
            this.CO_tb_PermisosRoles = new HashSet<CO_tb_PermisosRoles>();
            this.CO_tb_Usuarios5 = new HashSet<CO_tb_Usuarios>();
            this.CO_tb_Usuarios6 = new HashSet<CO_tb_Usuarios>();
        }
    
        public int IdRol { get; set; }
        public string NombreRol { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambio { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_PermisosRoles> CO_tb_PermisosRoles { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios1 { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios2 { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios3 { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Usuarios> CO_tb_Usuarios5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Usuarios> CO_tb_Usuarios6 { get; set; }
    }
}
