//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_tb_ventageneracional
    {
        public int IdVolumen { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<int> directos { get; set; }
        public Nullable<decimal> Volumen4taGen { get; set; }
        public Nullable<decimal> Volumen5aGen { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
    }
}
