//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_MenuDinamico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_tb_MenuDinamico()
        {
            this.CO_tb_MenuDinamico1 = new HashSet<CO_tb_MenuDinamico>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PadreId { get; set; }
        public string Nombre { get; set; }
        public string Archivo { get; set; }
        public string Carpeta { get; set; }
        public string Tipo { get; set; }
        public string Entre { get; set; }
        public string DescripcionMenu { get; set; }
        public int IdRol { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_MenuDinamico> CO_tb_MenuDinamico1 { get; set; }
        public virtual CO_tb_MenuDinamico CO_tb_MenuDinamico2 { get; set; }
    }
}
