//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CO_tb_Pantallas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_tb_Pantallas()
        {
            this.CO_tb_Pantallas1 = new HashSet<CO_tb_Pantallas>();
            this.CO_tb_PermisosRoles = new HashSet<CO_tb_PermisosRoles>();
        }

        public int IdPantalla { get; set; }
        public Nullable<int> PadreId { get; set; }
        public string NombrePantalla { get; set; }
        public bool checkeado { get; set; }
        public string Archivo { get; set; }
        public string Carpeta { get; set; }
        public string Tipo { get; set; }
        public string Entre { get; set; }
        public string DescripcionMenu { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambio { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Pantallas> CO_tb_Pantallas1 { get; set; }
        public virtual CO_tb_Pantallas CO_tb_Pantallas2 { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_PermisosRoles> CO_tb_PermisosRoles { get; set; }
    }
}
