//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_MovimientosSocio
    {
        public int id_MovimientosSocio { get; set; }
        public string partner_id { get; set; }
        public int id_Concepto { get; set; }
        public string comentario { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estatus { get; set; }
        public Nullable<int> folioCalculo { get; set; }
        public Nullable<int> Id_Periodo { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
        public Nullable<int> isDelete { get; set; }
    
        public virtual CO_tb_Conceptos CO_tb_Conceptos { get; set; }
    }
}
