//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_PermisosRoles
    {
        public int IdPermiso { get; set; }
        public int IdPantalla { get; set; }
        public int IdRol { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambio { get; set; }
    
        public virtual CO_tb_Pantallas CO_tb_Pantallas { get; set; }
        public virtual CO_tb_Roles CO_tb_Roles { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios1 { get; set; }
    }
}
