//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CO_tb_ImpuestoComision
    {
        public int id_Impuesto { get; set; }
        [DisplayName("Limite inferior")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<decimal> limiteInferior { get; set; }
        [DisplayName("Limite superior")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<decimal> limiteSuperior { get; set; }
        [DisplayName("Porcentaje")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<decimal> porcentaje { get; set; }
        [DisplayName("Cuota fija")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<decimal> coutaFija { get; set; }
        [DisplayName("Usuario")]
        public string usuario { get; set; }
        [DisplayName("Fecha movimiento")]
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
    }
}
