//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CO_tb_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_tb_Usuarios()
        {
            this.CO_tb_Pantallas = new HashSet<CO_tb_Pantallas>();
            this.CO_tb_Pantallas1 = new HashSet<CO_tb_Pantallas>();
            this.CO_tb_PermisosRoles = new HashSet<CO_tb_PermisosRoles>();
            this.CO_tb_PermisosRoles1 = new HashSet<CO_tb_PermisosRoles>();
            this.CO_tb_Roles = new HashSet<CO_tb_Roles>();
            this.CO_tb_Roles1 = new HashSet<CO_tb_Roles>();
            this.CO_tb_Roles2 = new HashSet<CO_tb_Roles>();
            this.CO_tb_Roles3 = new HashSet<CO_tb_Roles>();
            this.CO_tb_Roles4 = new HashSet<CO_tb_Roles>();
            this.CO_tb_Usuarios1 = new HashSet<CO_tb_Usuarios>();
            this.CO_tb_Usuarios11 = new HashSet<CO_tb_Usuarios>();
        }

        public int IdUsuario { get; set; }
        public int IdRol { get; set; }
        [DisplayName("Usuario")]
        public string NombreUsuario { get; set; }
        public string Correo { get; set; }
        [DisplayName("Contraseña")]
        public string Password { get; set; }
        [DisplayName("Confirma el Password")]
        public string ConfirmaPass { get; set; }
        public Nullable<int> Id_Pais { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambio { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Pantallas> CO_tb_Pantallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Pantallas> CO_tb_Pantallas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_PermisosRoles> CO_tb_PermisosRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_PermisosRoles> CO_tb_PermisosRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Roles> CO_tb_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Roles> CO_tb_Roles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Roles> CO_tb_Roles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Roles> CO_tb_Roles3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Roles> CO_tb_Roles4 { get; set; }
        public virtual CO_tb_Roles CO_tb_Roles5 { get; set; }
        public virtual CO_tb_Roles CO_tb_Roles6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Usuarios> CO_tb_Usuarios1 { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_Usuarios> CO_tb_Usuarios11 { get; set; }
        public virtual CO_tb_Usuarios CO_tb_Usuarios3 { get; set; }
    }
}
