//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CO_tb_Conceptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_tb_Conceptos()
        {
            this.CO_tb_MovimientosSocio = new HashSet<CO_tb_MovimientosSocio>();
        }
    
        public int id_Concepto { get; set; }
        [DisplayName("Descripcion")]
        public string descripcion { get; set; }
        [DisplayName("Tipo")]
        public string tipo { get; set; }
        [DisplayName("Es gravable")]
        public short gravable { get; set; }
        [DisplayName("Pago en especie")]
        public short pagoEspecie { get; set; }
        [DisplayName("Estatus")]
        public short estatus { get; set; }
        [DisplayName("Usuario")]
        public string usuario { get; set; }
        [DisplayName("Fecha Movimiento")]
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_tb_MovimientosSocio> CO_tb_MovimientosSocio { get; set; }
    }
}
