//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_tb_Periodos
    {
        public int Id_Periodo { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public int Quincena { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string Mensaje { get; set; }
        public string UsuarioUltMod { get; set; }
        public Nullable<System.DateTime> F_UltMod { get; set; }
        public Nullable<double> Pagado { get; set; }
        public Nullable<System.DateTime> F_Pagado { get; set; }
        public string Usuario_Pagado { get; set; }
        public int Id_PeriodoComision { get; set; }
        public string Id_Empresa { get; set; }
    }
}
