//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EVO_PTEntities : DbContext
    {
        public EVO_PTEntities()
            : base("name=EVO_PTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CU_tb_Periodos> CU_tb_Periodos { get; set; }
        public virtual DbSet<IN_tb_DtlMovInv> IN_tb_DtlMovInv { get; set; }
        public virtual DbSet<IN_tb_MovInventario> IN_tb_MovInventario { get; set; }
        public virtual DbSet<PR_tb_GanadoresPromocion> PR_tb_GanadoresPromocion { get; set; }
        public virtual DbSet<PR_tb_Param_Prom> PR_tb_Param_Prom { get; set; }
        public virtual DbSet<PR_tb_Promocion> PR_tb_Promocion { get; set; }
    }
}
