//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tb_Promocion
    {
        public int Id_Promocion { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public string Premio { get; set; }
        public Nullable<int> Cantidad_1 { get; set; }
        public string Premio_1 { get; set; }
        public Nullable<int> Cantidad_2 { get; set; }
        public string Premio_2 { get; set; }
        public Nullable<int> Cantidad_3 { get; set; }
        public string Premio_3 { get; set; }
        public Nullable<int> Cantidad_4 { get; set; }
        public string Premio_4 { get; set; }
        public Nullable<int> Cantidad_5 { get; set; }
        public string Premio_5 { get; set; }
        public string Usuario_Creacion { get; set; }
        public System.DateTime F_Creacion { get; set; }
        public string Host_Creacion { get; set; }
        public string Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> F_Modificacion { get; set; }
        public string Host_Modificacion { get; set; }
        public Nullable<int> Cantidad_6 { get; set; }
        public string Premio_6 { get; set; }
        public Nullable<int> Cantidad_7 { get; set; }
        public string Premio_7 { get; set; }
        public string Id_Empresa { get; set; }
    }
}
