//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tb_Param_Prom
    {
        public int Id_Reg { get; set; }
        public int Id_Periodo { get; set; }
        public int Id_Condicion { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public int Quincena { get; set; }
        public string Descripcion { get; set; }
        public int Id_Promocion { get; set; }
        public decimal Condicion1 { get; set; }
        public decimal Condicion2 { get; set; }
        public string Usuario_Creacion { get; set; }
        public System.DateTime F_Creacion { get; set; }
        public string Host_Creacion { get; set; }
        public string Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> F_Modificacion { get; set; }
        public string Host_Modificacion { get; set; }
        public int Socio_Tipo { get; set; }
        public Nullable<int> Relacion_Condicion { get; set; }
        public string Id_Empresa { get; set; }
    }
}
