//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tb_GanadoresPromocion
    {
        public int Id_Reg { get; set; }
        public string Id_Cliente { get; set; }
        public int Id_Periodo { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public Nullable<int> Quincena { get; set; }
        public int Id_Condicion { get; set; }
        public Nullable<decimal> Compras { get; set; }
        public Nullable<System.DateTime> F_PrimerCompra { get; set; }
        public string Id_MovInv { get; set; }
        public Nullable<int> Generar_Traspaso { get; set; }
        public string Usuario_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public string Id_Empresa { get; set; }
    }
}
