//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_tb_cdaVentas
    {
        public int Mes { get; set; }
        public string entered_by { get; set; }
        public Nullable<decimal> Total_venta { get; set; }
        public System.DateTime f_proceso { get; set; }
    }
}
