//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_tb_cdaVenta
    {
        public int iD_Venta { get; set; }
        public string Partner_id { get; set; }
        public Nullable<int> Id_Periodo { get; set; }
        public Nullable<decimal> Total_Venta { get; set; }
        public string Id_UserXen { get; set; }
        public Nullable<int> Id_Almacen { get; set; }
        public string Almacen { get; set; }
        public Nullable<int> Id_Responsable { get; set; }
        public Nullable<decimal> Regla { get; set; }
        public Nullable<int> Id_Politica { get; set; }
    }
}
