//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TMP_CALCULO_PREMIOS
    {
        public Nullable<int> RankLastPeriod_ID { get; set; }
        public int Mes { get; set; }
        public int Quincena { get; set; }
        public int Id_Pais { get; set; }
        public string Pais { get; set; }
        public int idPeriodo { get; set; }
        public string Partnetid { get; set; }
        public string nombrePartner { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> puntos { get; set; }
        public string Grado { get; set; }
        public string Bloque { get; set; }
        public string PRODUCTOS { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<bool> PedidoGenerado { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> Id_Pedido { get; set; }
    }
}
