//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_ImpuestoComision
    {
        public int id_Impuesto { get; set; }
        public Nullable<decimal> limiteInferior { get; set; }
        public Nullable<decimal> limiteSuperior { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<decimal> coutaFija { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
    }
}
