//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioComisiones.proxie.Comisiones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxie.Comisiones.IComisiones")]
    public interface IComisiones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComisiones/confirmarPrestamo", ReplyAction="http://tempuri.org/IComisiones/confirmarPrestamoResponse")]
        void confirmarPrestamo(int idPrestamo, int idPartner, int accionSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComisiones/confirmarPrestamo", ReplyAction="http://tempuri.org/IComisiones/confirmarPrestamoResponse")]
        System.Threading.Tasks.Task confirmarPrestamoAsync(int idPrestamo, int idPartner, int accionSolicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComisionesChannel : servicioComisiones.proxie.Comisiones.IComisiones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComisionesClient : System.ServiceModel.ClientBase<servicioComisiones.proxie.Comisiones.IComisiones>, servicioComisiones.proxie.Comisiones.IComisiones {
        
        public ComisionesClient() {
        }
        
        public ComisionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComisionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComisionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComisionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void confirmarPrestamo(int idPrestamo, int idPartner, int accionSolicitud) {
            base.Channel.confirmarPrestamo(idPrestamo, idPartner, accionSolicitud);
        }
        
        public System.Threading.Tasks.Task confirmarPrestamoAsync(int idPrestamo, int idPartner, int accionSolicitud) {
            return base.Channel.confirmarPrestamoAsync(idPrestamo, idPartner, accionSolicitud);
        }
    }
}
